name: swifty_companion
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: ^3.7.0

dependencies:
  flutter:
    sdk: flutter
  firebase_core: ^3.13.0
  flutter_dotenv: ^5.2.1
  flutter_hooks: ^0.21.2
  flutter_svg: ^2.1.0
  http: ^1.3.0
  oauth2_client: ^4.1.0
  percent_indicator: ^4.2.5
  provider: ^6.1.4
  skeletonizer: ^1.4.3
  syncfusion_flutter_charts: ^29.1.39
  timeago: ^3.7.0
  url_launcher: ^6.3.1
  xml2json: ^6.2.7
  dio: ^5.8.0+1
  cloud_firestore: ^5.6.7
  cached_network_image: ^3.4.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true
  assets:
    - .env
    - assets/images/
    - assets/clustersSvg/